services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=ykYtZb2wyBDCU'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=synorya'
      - 'POSTGRES_PASSWORD=KkjgjsBB2rCqz'
      - 'POSTGRES_USER=reopiya'
    ports:
      - '5432'
